# Welcome to Serverless!
#™
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: covidsource
app: covidsource
org: hrushka

provider:
  name: aws
  runtime: nodejs12.x
  tag: c19.dev
  region: us-east-1
  stage: dev
  memorySize: 256
  versionFunctions: false
  environment:
    #aurora
    AURORA_HOST: ${self:custom.AURORA.HOST}
    AURORA_PORT: ${self:custom.AURORA.PORT}
    #datastore
    DB_NAME: ${self:custom.DB_NAME}
    USERNAME: ${self:custom.USERNAME}
    PASSWORD: ${self:custom.PASSWORD}
    #custom
    BATCH_SIZE: 100
custom:
  # Pull in config file for custom vars per stage
  stage: ${opt:stage, self:provider.stage}
  stageConfig: ${file(./serverconfig.yaml):${self:custom.stage}}
  prune:
    automatic: true
    includeLayers: true
    number: 3
    
  customDomain:
    domainName: ${self:custom.stageConfig.domainName}
    state: ${self:provider.stage}
    basePath: ''
    createRoute53Record: true
    
  DB_NAME: ${self:custom.stageConfig.database.name}
  USERNAME: ${self:custom.stageConfig.database.username}
  PASSWORD: ${self:custom.stageConfig.database.password}
  AURORA:
    HOST:
      Fn::GetAtt: [AuroraRDSCluster, Endpoint.Address]
    PORT:
      Fn::GetAtt: [AuroraRDSCluster, Endpoint.Port]
    VPC_CIDR: 10
  #cfnRole: ${self:custom.stageConfig.cfnRole}
# Added in to support the API going out on our custom domain
#
plugins:
  - serverless-domain-manager
  - serverless-pseudo-parameters
  - serverless-prune-plugin
resources:
  Resources:
    ServerlessInternetGateway: ${file(./resource/ServerlessInternetGateway.yml)}
    ServerlessVPC: ${file(./resource/ServerlessVPC.yml)}
    ServerlessVPCGA: ${file(./resource/ServerlessVPCGA.yml)}
    ServerlessSubnetA: ${file(./resource/ServerlessSubnetA.yml)}
    ServerlessSubnetB: ${file(./resource/ServerlessSubnetB.yml)}
    ServerlessSubnetC: ${file(./resource/ServerlessSubnetC.yml)}
    ServerlessSubnetGroup: ${file(./resource/ServerlessSubnetGroup.yml)}
    ServerlessSecurityGroup: ${file(./resource/ServerlessSecurityGroup.yml)}
    RouteTablePublic: ${file(./resource/RouteTablePublic.yml)}
    RoutePublic: ${file(./resource/RoutePublic.yml)}
    RouteTableAssociationSubnetA: ${file(./resource/RouteTableAssociationSubnetA.yml)}
    RouteTableAssociationSubnetB: ${file(./resource/RouteTableAssociationSubnetB.yml)}
    RouteTableAssociationSubnetC: ${file(./resource/RouteTableAssociationSubnetC.yml)}

    AuroraRDSClusterParameter: ${file(./resource/AuroraRDSClusterParameter.yml)}
    AuroraRDSInstanceParameter: ${file(./resource/AuroraRDSInstanceParameter.yml)}
    AuroraRDSCluster: ${file(./resource/AuroraRDSCluster.yml)}
    AuroraRDSInstance: ${file(./resource/AuroraRDSInstance.yml)}

# The list of functions for the domain
#
functions:
  # Data ingestion pipeline functions
  ingest_ctp:
    handler: handler_data.ingest_ctp
    timeout: 30
    events:
      - schedule: rate(1 hour)
  ingest_us:
    handler: handler_data.ingest_us
    timeout: 30
  ingest_nyt:
    handler: handler_data.ingest_nyt
    timeout: 30
    events:
      - schedule: rate(3 hours)

  # API Endpoints for the c19api.com domain
  #
  test:
    handler: handler_api.test
    events:
      - http:
          path: /
          method: get
  search:
    handler: handler_api.search
    events:
      - http:
          path: search
          method: post
  query:
    handler: handler_api.query
    events:
      - http:
          path: query
          method: post
  annotations:
    handler: handler_api.annotations
    events:
      - http:
          path: annotations
          method: post
  tag-keys:
    handler: handler_api.tagKeys
    events:
      - http:
          path: tag-keys
          method: post
  tag-values:
    handler: handler_api.tagValues
    events:
      - http:
          path: tag-values
          method: post