{
 "title": "COVID-19 US State Data",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "state",
    "label": "Select a State",
    "query": "select state_abbv as __value, state_full as __text from data_us_data;"
   },
   {
    "name": "population",
    "query": "SELECT SUM(usc_population_2019) as pop\nFROM data_us_data\nWHERE\n  state_abbv IN ($state)"
   },
   {
    "name": "density",
    "query": "SELECT AVG(usc_density_2019) as density\nFROM data_us_data\nWHERE\n  state_abbv IN ($state)"
   },
   {
    "name": "total_cases",
    "query": "SELECT SUM(cases) as cases\nFROM data_nyt_county \nWHERE state_abbv IN ($state) \nAND date = (SELECT MAX( date ) FROM data_nyt_county WHERE state_abbv IN ($state))"
   },
   {
    "name": "total_deaths",
    "query": "SELECT SUM(deaths) as deaths\nFROM data_nyt_county \nWHERE state_abbv IN ($state) \nAND date = (SELECT MAX( date ) FROM data_nyt_county WHERE state_abbv IN ($state))"
   }
  ]
 },
 "panels": [
  { "title": "Rate Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prevalence Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  CAST(SUM(positive) / $population as DECIMAL(10,8)) AS \"Prevalence\"\nFROM data_ctp\nWHERE\n  state IN($state)AND $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Incidence Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  CAST((SUM(positiveIncrease) / $population) * 1000 as DECIMAL(10,8)) AS \"Incidence Rate\"\nFROM data_ctp\nWHERE\n  state IN($state) AND $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Case Fatality Rate (CFR)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  CAST(SUM(death) / SUM(positive) as DECIMAL(10,8)) AS \"CFR\"\nFROM data_ctp\nWHERE\n  state IN($state) AND $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Prevalence Rate Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  CAST(SUM(positive) / $population as DECIMAL(10,8)) AS \"Prevalence\"\nFROM data_ctp\nWHERE\n  state IN($state)AND $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Incidence Rate Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  CAST((SUM(positiveIncrease) / $population) * 1000 as DECIMAL(10,8)) AS \"Incidence Rate\"\nFROM data_ctp\nWHERE\n  state IN($state) AND $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "CFR Over Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  CAST(SUM(death) / SUM(positive) as DECIMAL(10,8)) AS \"CFR\"\nFROM data_ctp\nWHERE\n  state IN($state) AND $__timeFilter(date)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  { "title": "Testing & Mortality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Positive Cases",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(positive) AS \"positive\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Total Tests",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(totalTestResults) AS \"totalTestResults\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "County-level Impact",
   "type": "table",
   "description": "This data is compiled by The New York Times. County-level totals may differ from other data sets present on the dashboard.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT state_abbv as State, county as County, cases as Cases, ROUND((cases / $total_cases) * 100,2) as 'Case %', deaths as Deaths, ROUND((deaths / $total_deaths) * 100,2) as 'Deaths %' from data_nyt_county WHERE state_abbv IN ($state) AND date = (SELECT MAX( date ) FROM data_nyt_county WHERE state_abbv IN ($state)) ORDER BY cases DESC;"
    }
   ]
  },
  {
   "title": "Total Deaths",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(death) AS \"death\"\nFROM data_ctp\nWHERE\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Tests per Thousand",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  (SUM(totalTestResults) / ($population/1000)) AS \"totalTestResults\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Testing Data",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(totalTestResults) AS \"Total\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(positive) AS \"Positive\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(negative) AS \"Negative\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(pending) AS \"Pending\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Hospitalizations & Deaths",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(hospitalizedCumulative) AS \"Hospitalized\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(death) AS \"Deaths\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "Daily Positives vs. Daily Tests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(totalTestResultsIncrease) AS \"Tests\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    },
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(positiveIncrease) AS \"Positives\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "title": "New Daily Deaths",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  sum(deathIncrease) AS \"Deaths\"\nFROM data_ctp\nWHERE\n  $__timeFilter(date) AND\n  state IN ($state)\nGROUP BY 1\nORDER BY $__timeGroup(date,$__interval)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "content": "<div style=\"font-family: 'Source Code Pro', monospace;text-align:center;\">\n</br>\n<p>This data is sourced from <a href=\"https://covidtracking.com/\" target=\"_blank\">The COVID Tracking Project</a>, <a href=\"https://www.nytimes.com/interactive/2020/us/coronavirus-us-cases.html\" target=\"_blank\">The New York Times</a>, the <a href=\"https://census.gov\" target=\"_blank\">US Census Bureau</a> and the <a href=\"https://covid19.healthdata.org/projections\" target=\"_blank\">IHME</a>.\n</div>"
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 30 },
   "content": "<div style=\"font-family: 'Source Code Pro', monospace;text-align:center;margin-top:10px;\">\n<table style=\"width:100%;border:none !important;margin-top:10px;\" border=0> \n    <tr style=\"text-align:center;border:none !important;\"> \n        <td width=\"30%\" style=\"border:none !important;\"><h1><a style=\"color:darkgray;\" href=\"https://www.youtube.com/channel/UC_D6qpdhkoJJZE_CGFyVhog\" target=\"_blank\"><img height=30 src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Logo_of_YouTube_%282015-2017%29.svg/502px-Logo_of_YouTube_%282015-2017%29.svg.png\"/></a></h1><small>watch the build</small></td>\n        <td width=\"30%\" style=\"border:none !important;\"><h1><a style=\"color:darkgray;\" href=\"https://www.twitch.tv/hrudotsh\" target=\"_blank\"><img height=30 src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Twitch_logo.svg/455px-Twitch_logo.svg.png\"/></a></h1><small>stream it live</small></td>\n        <td width=\"30%\" style=\"border:none !important;\"><h1><a style=\"color:darkgray;\" href=\"https://github.com/hrushka/covidsource\" target=\"_blank\"><img width=80 src=\"https://github.githubassets.com/images/modules/logos_page/GitHub-Logo.png\"/></a></h1><small>get the code</small></td>\n    </tr>\n</table>\n<small>Follow, use and contribute. ❤ &mdash; Matt <<a href=\"mailto:c19@hru.sh\">c19@hru.sh</a>><br/>v1.20200402</small>\n</div>"
  }
 ]
}